# Generated by Django 4.2.11 on 2026-04-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_about_user_avatar_user_github_url_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["name"],
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
