# Generated by Django 4.2.11 on 2026-04-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_github_url_project_participants_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
    ]
